version: "3.9"
networks:
  defaultOfvpNetwork:
volumes:
  mongoStorage:
  sshStorage:

services:
  mongodb:
    image: mongo
    restart: always
    command: "--bind_ip_all --port 27017 --noauth --quiet --logpath /dev/null"
    networks: [defaultOfvpNetwork]
    volumes: [mongoStorage:/data/db]

  maneger:
    image: ghcr.io/ofvp-project/maneger:next
    ports: [3000:3000/tcp]
    networks: [defaultOfvpNetwork]
    depends_on: [mongodb]
    environment:
      NODE_ENV: "development"
      MONGO_URL: "mongodb://mongodb:27017/ofvp"
      PASSWORD_SECERET: "dev"
      COOKIE_SECRET: "dev"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  ssh:
    image: ghcr.io/ofvp-project/ssh-server:next
    restart: always
    depends_on: [maneger]
    networks: [defaultOfvpNetwork]
    ports: [2222:22/tcp]
    volumes: [sshStorage:/data]
    environment:
      PASSWORD_ENCRYPT: "dev"
      NODE_ENV: "development"
      DAEMON_HOST: "http://maneger:5000"
      DAEMON_USERNAME: ""
      DAEMON_PASSWORD: ""

  webproxy:
    build: ./
    restart: always
    depends_on: [ssh]
    networks: [defaultOfvpNetwork]
    ports: [8080:80/tcp]
    volumes:
      - ./:/app
    entrypoint: "npm run dev"
    environment:
      SSH_HOST: "ssh:22"
      STATUS_MESSAGE: "By Devs"
      LOG_LEVEL: "2"
      PORT_LISTEN: "80"