name: Test/Build Docker Image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  release:
    types:
      - released
env:
  docker_archs: linux/amd64,linux/arm64
  NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
jobs:
  BuildTest:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Image Build Environment
        run: |
          if [[ "${{ github.event_name }}" == 'release' ]]; then
            echo "Building release image"
            echo IMAGE_TAG=latest >> $GITHUB_ENV
          else
            echo "Building development image"
            echo IMAGE_TAG=nightly >> $GITHUB_ENV
          fi
          cat $GITHUB_ENV

      - name: Build and push BadVPN image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
          target: badvpn
          tags: ghcr.io/ofvp-project/badvpn:${{ env.IMAGE_TAG || "latest" }}
          platforms: ${{ env.docker_archs }}

      - name: Build and push WebProxy image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'push' || github.event_name == 'release' }}
          target: webproxy
          tags: ghcr.io/ofvp-project/webproxy:${{ env.IMAGE_TAG || "latest" }}
          platforms: ${{ env.docker_archs }}
