name: Build Docker Image
on:
  release:
    types: [released]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          submodules: true

      - name: Setup QEMU to Docker
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login into registry Github Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push WebProxy image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=gha,scope=${{ github.ref }}_ofvp_daemon_${{ github.repository }}
          cache-to: type=gha,mode=max,scope=${{ github.ref }}_ofvp_daemon_${{ github.repository }}
          platforms: linux/amd64,linux/arm64
          context: .
          tags: ghcr.io/ofvp-project/webproxy:latest
          push: true